/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package opennlp.tools.formats;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.Base64;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;

import opennlp.tools.formats.MorfologikDictionaryReader.BaseFormEncoding;
import opennlp.tools.lemmatizer.DictionaryLemmatizer;

/**
 * Validates the clean-room {@link MorfologikDictionaryReader}. The base-form decode cases and the
 * end-to-end CFSA2 dictionary below were generated by morfologik's own encoder and serializer, so
 * the reader is checked against that library's output rather than against restated assumptions.
 */
public class MorfologikDictionaryReaderTest {

  // A CFSA2 dictionary of cat+A+NN, cats+B+NNS, dogs+B+NNS, mice+Douse+NN (SUFFIX encoder, '+'
  // separator, ISO-8859-1), built by morfologik's CFSA2Serializer.
  private static final String DICTIONARY_BASE64 =
      "XGZzYcYABxIAdXRtaWdkYVNEQkFvZWNzTitAXgMOHwYVw8TOzdHJzMHPzdHQcADMxc/RytHQ0GgAx8KRTxhLEQ==";

  // The same dictionary serialized in the older FSA5 format, to prove both formats are read.
  private static final String FSA5_DICTIONARY_BASE64 =
      "XGZzYQVfKwIAAABeBmPIAWQwAW0GaQZjBmUGKwZEBm8GdQZzBmUGKwZOBk4DAG8G"
          + "ZwZzBisGQgYrBk4GTgZTAwBhBnQGKxgCc2IBQfoA";

  private static byte[] iso(String s) {
    return s.getBytes(StandardCharsets.ISO_8859_1);
  }

  /** Each encoder recovers the base form morfologik encoded. */
  @ParameterizedTest
  @CsvSource({
      "SUFFIX, cats,    B,      cat",
      "SUFFIX, mice,    Douse,  mouse",
      "SUFFIX, foobar,  Gbar,   bar",
      "SUFFIX, cat,     A,      cat",
      "PREFIX, cats,    AB,     cat",
      "PREFIX, foobar,  DA,     bar",
      "PREFIX, unhappy, CA,     happy",
      "PREFIX, mice,    ADouse, mouse",
      "INFIX,  cats,    AAB,    cat",
      "INFIX,  foobar,  ADA,    bar",
      "INFIX,  unhappy, ACA,    happy",
      "INFIX,  mice,    AADouse, mouse",
      "NONE,   cats,    cat,    cat",
  })
  void testDecodeBaseForm(String encoder, String form, String encoded, String base) {
    final byte[] decoded = MorfologikDictionaryReader.decodeBaseForm(
        iso(form), iso(encoded), BaseFormEncoding.valueOf(encoder));
    Assertions.assertEquals(base, new String(decoded, StandardCharsets.ISO_8859_1));
  }

  private static DictionaryLemmatizer dictionary() throws IOException {
    return MorfologikDictionaryReader.read(
        new ByteArrayInputStream(Base64.getDecoder().decode(DICTIONARY_BASE64)),
        (byte) '+', BaseFormEncoding.SUFFIX, StandardCharsets.ISO_8859_1);
  }

  /** The CFSA2 dictionary lemmatizes each surface form under its tag; misses yield "O". */
  @Test
  void testReadsCfsa2DictionaryEndToEnd() throws IOException {
    final DictionaryLemmatizer lemmatizer = dictionary();

    Assertions.assertArrayEquals(new String[] {"cat"},
        lemmatizer.lemmatize(new String[] {"cats"}, new String[] {"NNS"}));
    Assertions.assertArrayEquals(new String[] {"dog"},
        lemmatizer.lemmatize(new String[] {"dogs"}, new String[] {"NNS"}));
    Assertions.assertArrayEquals(new String[] {"mouse"},
        lemmatizer.lemmatize(new String[] {"mice"}, new String[] {"NN"}));
    Assertions.assertArrayEquals(new String[] {"cat"},
        lemmatizer.lemmatize(new String[] {"cat"}, new String[] {"NN"}));
    Assertions.assertArrayEquals(new String[] {"O"},
        lemmatizer.lemmatize(new String[] {"mice"}, new String[] {"NNS"}));
  }

  /** The same dictionary in the older FSA5 format is read identically. */
  @Test
  void testReadsFsa5DictionaryEndToEnd() throws IOException {
    final DictionaryLemmatizer lemmatizer = MorfologikDictionaryReader.read(
        new ByteArrayInputStream(Base64.getDecoder().decode(FSA5_DICTIONARY_BASE64)),
        (byte) '+', BaseFormEncoding.SUFFIX, StandardCharsets.ISO_8859_1);

    Assertions.assertArrayEquals(new String[] {"mouse"},
        lemmatizer.lemmatize(new String[] {"mice"}, new String[] {"NN"}));
    Assertions.assertArrayEquals(new String[] {"cat"},
        lemmatizer.lemmatize(new String[] {"cats"}, new String[] {"NNS"}));
  }

  /** The separator, encoding, and encoder are taken from .info metadata when supplied. */
  @Test
  void testReadsWithInfoMetadata() throws IOException {
    final String info = "fsa.dict.separator=+\n"
        + "fsa.dict.encoding=iso-8859-1\n"
        + "fsa.dict.encoder=suffix\n";
    final InputStream dict = new ByteArrayInputStream(Base64.getDecoder().decode(DICTIONARY_BASE64));

    final DictionaryLemmatizer lemmatizer = MorfologikDictionaryReader.read(
        dict, new ByteArrayInputStream(info.getBytes(StandardCharsets.ISO_8859_1)));

    Assertions.assertArrayEquals(new String[] {"mouse"},
        lemmatizer.lemmatize(new String[] {"mice"}, new String[] {"NN"}));
  }

  /** Missing required metadata fails loudly. */
  @Test
  void testMissingMetadataKeyRejected() {
    final String info = "fsa.dict.separator=+\n";
    final InputStream dict = new ByteArrayInputStream(Base64.getDecoder().decode(DICTIONARY_BASE64));
    Assertions.assertThrows(IllegalArgumentException.class, () -> MorfologikDictionaryReader.read(
        dict, new ByteArrayInputStream(info.getBytes(StandardCharsets.ISO_8859_1))));
  }

  /** A null dictionary stream is rejected at the boundary. */
  @Test
  void testNullDictionaryRejected() {
    Assertions.assertThrows(IllegalArgumentException.class, () -> MorfologikDictionaryReader.read(
        null, (byte) '+', BaseFormEncoding.SUFFIX, StandardCharsets.ISO_8859_1));
  }
}
