// CHECKSTYLE:OFF
/*

Copyright (c) 2001, Dr Martin Porter
Copyright (c) 2002, Richard Boulton
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice,
    * this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
    * notice, this list of conditions and the following disclaimer in the
    * documentation and/or other materials provided with the distribution.
    * Neither the name of the copyright holders nor the names of its contributors
    * may be used to endorse or promote products derived from this software
    * without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

 */

// Generated by Snowball (build from 9a22f0d3f44cda36677829328fe2642750114d57)
package opennlp.tools.stemmer.snowball;

/**
 * Internal class used by Snowball stemmers
 */
public class Among {

  /**
   * A routine of a {@link SnowballProgram} that accepts or rejects a matched
   * substring.
   *
   * @param <T> The stemmer type the routine belongs to.
   */
  @FunctionalInterface
  public interface Condition<T extends SnowballProgram> {
    boolean test(T program);
  }

  public Among(String s, int substring_i, int result) {
    this.s = s.toCharArray();
    this.substring_i = substring_i;
    this.result = result;
    this.method = null;
  }

  /**
   * @param condition The routine to call on the stemmer once {@code s} matched,
   *                  for instance {@code finnishStemmer::r_VI}. Must not be {@code null}.
   * @param <T> The stemmer type the routine belongs to; the stemmer that uses this
   *            {@link Among} must be of that type.
   */
  @SuppressWarnings("unchecked")
  public <T extends SnowballProgram> Among(String s, int substring_i, int result, Condition<T> condition) {
    this.s = s.toCharArray();
    this.substring_i = substring_i;
    this.result = result;
    if (condition == null) {
      throw new IllegalArgumentException("condition must not be null");
    }
    this.method = (Condition<SnowballProgram>) condition;
  }

  final char[] s; /* search string */
  final int substring_i; /* index to longest matching substring */
  final int result; /* result of the lookup */

  // Make sure this is not accessible outside package for Java security reasons!
  final Condition<SnowballProgram> method; /* routine to call if substring matches */
};
