/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.HexFormat;
import java.util.List;

/** Generates the normalized Unicode 18 emoji sequence inventory used at runtime. */
public final class UnicodeEmojiSequenceGenerator {

  private static final String EMOJI_TEST_SHA256 =
      "8f3735cda1f92a779d78af67cf86066bb1f07143dc22f2ac29394d9bc57ab21a";
  private static final String EMOJI_DATA_SHA256 =
      "80d00f8e616a0ef27fd6b8de3b758c06383b5d917e2977709578e68baf733bf1";

  private UnicodeEmojiSequenceGenerator() {
  }

  public static void main(String[] args) throws Exception {
    if (args.length != 3) {
      throw new IllegalArgumentException(
          "usage: UnicodeEmojiSequenceGenerator emoji-test.txt emoji-data.txt output.txt");
    }
    Path emojiTest = Path.of(args[0]);
    Path emojiData = Path.of(args[1]);
    verifySource(emojiTest, EMOJI_TEST_SHA256);
    verifySource(emojiData, EMOJI_DATA_SHA256);
    verifyVersion(emojiTest, "18.0");
    verifyVersion(emojiData, "18.0.0");

    List<String> sequences = readFullyQualifiedSequences(emojiTest);
    List<String> components = readComponentRanges(emojiData);
    List<String> output = new ArrayList<>(sequences.size() + components.size() + 9);
    output.add("# Unicode Emoji 18.0 fully-qualified sequences");
    output.add("# Derived from emoji-test.txt and emoji-data.txt under Unicode License V3.");
    output.add("# emoji-test.txt SHA-256: " + EMOJI_TEST_SHA256);
    output.add("# emoji-data.txt SHA-256: " + EMOJI_DATA_SHA256);
    output.add("# S records are exact sequences; C records are Emoji_Component ranges.");
    output.add("# Generated by dev/UnicodeEmojiSequenceGenerator.java; do not edit.");
    for (String sequence : sequences) {
      output.add("S;" + sequence);
    }
    for (String component : components) {
      output.add("C;" + component);
    }
    Files.createDirectories(Path.of(args[2]).getParent());
    Files.write(Path.of(args[2]), output, StandardCharsets.US_ASCII);
    System.out.printf("wrote %d sequences and %d component ranges%n",
        sequences.size(), components.size());
  }

  private static List<String> readFullyQualifiedSequences(Path source) throws IOException {
    List<String> result = new ArrayList<>();
    for (String line : Files.readAllLines(source, StandardCharsets.UTF_8)) {
      int semicolon = line.indexOf(';');
      int comment = line.indexOf('#', semicolon + 1);
      if (semicolon < 0 || comment < 0) {
        continue;
      }
      String status = line.substring(semicolon + 1, comment).trim();
      if (status.equals("fully-qualified")) {
        result.add(normalizeCodePoints(line.substring(0, semicolon)));
      }
    }
    if (result.size() != 3963) {
      throw new IOException("expected 3963 fully-qualified sequences, found " + result.size());
    }
    return result;
  }

  private static List<String> readComponentRanges(Path source) throws IOException {
    List<String> result = new ArrayList<>();
    for (String line : Files.readAllLines(source, StandardCharsets.UTF_8)) {
      int semicolon = line.indexOf(';');
      int comment = line.indexOf('#', semicolon + 1);
      if (semicolon < 0 || comment < 0) {
        continue;
      }
      if (line.substring(semicolon + 1, comment).trim().equals("Emoji_Component")) {
        result.add(normalizeRange(line.substring(0, semicolon)));
      }
    }
    if (result.isEmpty()) {
      throw new IOException("emoji-data.txt has no Emoji_Component ranges");
    }
    return result;
  }

  private static String normalizeCodePoints(String value) throws IOException {
    StringBuilder normalized = new StringBuilder();
    int start = -1;
    for (int i = 0; i <= value.length(); i++) {
      if (i == value.length() || Character.isWhitespace(value.charAt(i))) {
        if (start >= 0) {
          if (normalized.length() > 0) {
            normalized.append(' ');
          }
          normalized.append(formatCodePoint(parseHex(value.substring(start, i))));
          start = -1;
        }
      }
      else if (start < 0) {
        start = i;
      }
    }
    if (normalized.length() == 0) {
      throw new IOException("empty code point sequence");
    }
    return normalized.toString();
  }

  private static String normalizeRange(String value) throws IOException {
    String trimmed = value.trim();
    int dots = trimmed.indexOf("..");
    if (dots < 0) {
      return formatCodePoint(parseHex(trimmed));
    }
    return formatCodePoint(parseHex(trimmed.substring(0, dots))) + ".."
        + formatCodePoint(parseHex(trimmed.substring(dots + 2)));
  }

  private static int parseHex(String value) throws IOException {
    try {
      int codePoint = Integer.parseInt(value, 16);
      if (!Character.isValidCodePoint(codePoint)) {
        throw new IOException("invalid code point: " + value);
      }
      return codePoint;
    } catch (NumberFormatException e) {
      throw new IOException("invalid hexadecimal code point: " + value, e);
    }
  }

  private static String formatCodePoint(int codePoint) {
    return String.format("%04X", codePoint);
  }

  private static void verifyVersion(Path source, String expected) throws IOException {
    boolean found = Files.readAllLines(source, StandardCharsets.UTF_8).stream()
        .anyMatch(line -> line.equals("# Version: " + expected));
    if (!found) {
      throw new IOException(source + " is not Unicode Emoji version " + expected);
    }
  }

  private static void verifySource(Path source, String expected) throws IOException {
    try {
      String actual = HexFormat.of().formatHex(
          MessageDigest.getInstance("SHA-256").digest(Files.readAllBytes(source)));
      if (!actual.equals(expected)) {
        throw new IOException(source + " SHA-256 mismatch: expected " + expected
            + ", found " + actual);
      }
    } catch (NoSuchAlgorithmException e) {
      throw new IllegalStateException("SHA-256 is unavailable", e);
    }
  }
}
