/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package opennlp.subword.sentencepiece;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.stream.Stream;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assumptions.assumeTrue;

/**
 * Opt-in parity check against real pre-trained models, which are downloaded rather than bundled.
 *
 * <p>Point {@code -Dopennlp.subword.eval.dir} at a directory holding {@code <name>.model} files
 * with sibling {@code <name>.fixtures.tsv} files generated by the {@code gen_real_fixtures.py}
 * script from the test resources; every model found is asserted piece for piece. Without the
 * property the test is skipped.</p>
 */
class SentencePieceRealModelEvalTest {

  @Test
  void testRealModelParity() throws IOException {
    final String dir = System.getProperty("opennlp.subword.eval.dir");
    assumeTrue(dir != null && !dir.isBlank(),
        "set -Dopennlp.subword.eval.dir to run the real-model parity check");

    int models = 0;
    try (Stream<Path> files = Files.list(Path.of(dir))) {
      for (final Path model : files.filter(f -> f.toString().endsWith(".model")).sorted()
          .toList()) {
        final Path fixtures = Path.of(model.toString()
            .substring(0, model.toString().length() - ".model".length()) + ".fixtures.tsv");
        assumeTrue(Files.exists(fixtures), "no fixtures for " + model.getFileName());
        models++;
        assertModel(model, fixtures);
      }
    }
    assertTrue(models > 0, "the eval directory contains no models");
  }

  private static void assertModel(Path modelPath, Path fixturesPath) throws IOException {
    final SentencePieceTokenizer tokenizer = SentencePieceTokenizer.load(modelPath);
    final List<SentencePieceFixtures.Fixture> fixtures;
    try (BufferedReader reader = Files.newBufferedReader(fixturesPath, StandardCharsets.UTF_8)) {
      fixtures = SentencePieceFixtures.read(reader);
    }
    for (final SentencePieceFixtures.Fixture fixture : fixtures) {
      SentencePieceFixtures.assertFixture(tokenizer, fixture,
          modelPath.getFileName() + " input <" + fixture.input() + ">");
    }
    assertTrue(fixtures.size() >= 30, modelPath.getFileName() + " fixtures must not be truncated");
  }
}
