/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package opennlp.subword.sentencepiece;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.StringJoiner;
import java.util.concurrent.ConcurrentHashMap;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

import opennlp.tools.tokenize.SubwordPiece;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Asserts exact parity with the reference implementation: for every fixture input, the pieces,
 * ids, original-text spans, and the normalized form must equal what the reference produced for
 * the same bundled model. The fixtures were generated by {@code gen_fixtures.tsv}'s sibling
 * script (see the test resources) against the sentencepiece Python package.
 */
class SentencePieceParityTest {

  private static final Map<String, SentencePieceTokenizer> LOADED = new ConcurrentHashMap<>();

  static SentencePieceTokenizer tokenizer(String model) {
    return LOADED.computeIfAbsent(model, name -> {
      try (InputStream in = SentencePieceParityTest.class.getResourceAsStream(name + ".model")) {
        assertNotNull(in, "missing test resource " + name + ".model");
        return SentencePieceTokenizer.load(in);
      } catch (IOException e) {
        throw new IllegalStateException(e);
      }
    });
  }

  @ParameterizedTest
  @ValueSource(strings = {"tiny-unigram", "tiny-unigram-bytefb", "tiny-bpe",
      "tiny-unigram-identity", "tiny-unigram-suffix"})
  void testFixtureParity(String model) throws IOException {
    final SentencePieceTokenizer tokenizer = tokenizer(model);
    int lines = 0;
    for (final Fixture fixture : fixtures(model)) {
      lines++;
      final List<SubwordPiece> actual = tokenizer.encode(fixture.input);
      final String context = model + " input <" + fixture.input + ">";
      assertEquals(fixture.pieces.size(), actual.size(),
          context + " piece count; got " + actual);
      for (int i = 0; i < actual.size(); i++) {
        final SubwordPiece expected = fixture.pieces.get(i);
        final SubwordPiece got = actual.get(i);
        assertEquals(expected.piece(), got.piece(), context + " piece " + i);
        assertEquals(expected.id(), got.id(), context + " id of piece " + i);
        assertEquals(expected.start(), got.start(), context + " start of piece " + i);
        assertEquals(expected.end(), got.end(), context + " end of piece " + i);
      }
      assertEquals(fixture.normalized, tokenizer.normalize(fixture.input).toString(),
          context + " normalized form");
    }
    assertTrue(lines >= 30, "the fixture file must not be empty or truncated");
  }

  @ParameterizedTest
  @ValueSource(strings = {"tiny-unigram", "tiny-unigram-bytefb", "tiny-bpe",
      "tiny-unigram-identity", "tiny-unigram-suffix"})
  void testEmbeddedSelfTestSamples(String model) {
    final SentencePieceTokenizer tokenizer = tokenizer(model);
    final List<String> inputs = tokenizer.selfTestInputs();
    final List<String> expected = tokenizer.selfTestExpected();
    assertTrue(!inputs.isEmpty(), "the tiny models embed self-test samples");
    for (int i = 0; i < inputs.size(); i++) {
      final StringJoiner joined = new StringJoiner(" ");
      for (final String piece : tokenizer.encodeToPieces(inputs.get(i))) {
        joined.add(piece);
      }
      assertEquals(expected.get(i), joined.toString(),
          model + " self-test sample <" + inputs.get(i) + ">");
    }
  }

  private record Fixture(String input, List<SubwordPiece> pieces, String normalized) {
  }

  private static List<Fixture> fixtures(String model) throws IOException {
    final List<Fixture> fixtures = new ArrayList<>();
    try (InputStream in =
             SentencePieceParityTest.class.getResourceAsStream(model + ".fixtures.tsv")) {
      assertNotNull(in, "missing test resource " + model + ".fixtures.tsv");
      final BufferedReader reader =
          new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8));
      String line;
      while ((line = reader.readLine()) != null) {
        final String[] cols = line.split("\t", -1);
        final String input = unescape(cols[0]);
        final int count = Integer.parseInt(cols[1]);
        final List<SubwordPiece> pieces = new ArrayList<>(count);
        for (int i = 0; i < count; i++) {
          pieces.add(new SubwordPiece(unescape(cols[2 + i * 4]),
              Integer.parseInt(cols[3 + i * 4]), Integer.parseInt(cols[4 + i * 4]),
              Integer.parseInt(cols[5 + i * 4])));
        }
        fixtures.add(new Fixture(input, pieces, unescape(cols[2 + count * 4])));
      }
    }
    return fixtures;
  }

  private static String unescape(String s) {
    final StringBuilder out = new StringBuilder(s.length());
    for (int i = 0; i < s.length(); i++) {
      final char c = s.charAt(i);
      if (c == '\\' && i + 1 < s.length()) {
        i++;
        switch (s.charAt(i)) {
          case 't' -> out.append('\t');
          case 'n' -> out.append('\n');
          case 'r' -> out.append('\r');
          case '\\' -> out.append('\\');
          default -> throw new IllegalArgumentException("bad escape in fixture: " + s);
        }
      } else {
        out.append(c);
      }
    }
    return out.toString();
  }
}
