/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package opennlp.subword.sentencepiece;

import java.io.IOException;
import java.util.List;
import java.util.StringJoiner;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Asserts exact parity with the reference implementation: for every fixture input, the pieces,
 * ids, original-text spans, and the normalized form must equal what the reference produced for
 * the same bundled model. The fixtures were generated by the {@code gen_fixtures.py} script in
 * the test resources against the sentencepiece Python package.
 */
class SentencePieceParityTest {

  @ParameterizedTest
  @MethodSource("opennlp.subword.sentencepiece.SentencePieceFixtures#models")
  void testFixtureParity(String model) throws IOException {
    final SentencePieceTokenizer tokenizer = SentencePieceFixtures.tokenizer(model);
    int lines = 0;
    for (final SentencePieceFixtures.Fixture fixture : SentencePieceFixtures.fixtures(model)) {
      lines++;
      SentencePieceFixtures.assertFixture(tokenizer, fixture,
          model + " input <" + fixture.input() + ">");
    }
    assertTrue(lines >= 30, "the fixture file must not be empty or truncated");
  }

  @ParameterizedTest
  @MethodSource("opennlp.subword.sentencepiece.SentencePieceFixtures#models")
  void testEmbeddedSelfTestSamples(String model) {
    final SentencePieceTokenizer tokenizer = SentencePieceFixtures.tokenizer(model);
    final List<String> inputs = tokenizer.selfTestInputs();
    final List<String> expected = tokenizer.selfTestExpected();
    assertTrue(!inputs.isEmpty(), "the tiny models embed self-test samples");
    for (int i = 0; i < inputs.size(); i++) {
      final StringJoiner joined = new StringJoiner(" ");
      for (final String piece : tokenizer.encodeToPieces(inputs.get(i))) {
        joined.add(piece);
      }
      assertEquals(expected.get(i), joined.toString(),
          model + " self-test sample <" + inputs.get(i) + ">");
    }
  }
}
