/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package opennlp.subword.sentencepiece;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.stream.Stream;

import org.junit.jupiter.api.Test;

import opennlp.subword.SubwordPiece;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assumptions.assumeTrue;

/**
 * Opt-in parity check against real pre-trained models, which are downloaded rather than bundled.
 *
 * <p>Point {@code -Dopennlp.subword.eval.dir} at a directory holding {@code <name>.model} files
 * with sibling {@code <name>.fixtures.tsv} files generated by the {@code gen_real_fixtures.py}
 * script from the test resources; every model found is asserted piece for piece. Without the
 * property the test is skipped.</p>
 */
class SentencePieceRealModelEvalTest {

  @Test
  void testRealModelParity() throws IOException {
    final String dir = System.getProperty("opennlp.subword.eval.dir");
    assumeTrue(dir != null && !dir.isBlank(),
        "set -Dopennlp.subword.eval.dir to run the real-model parity check");

    int models = 0;
    try (Stream<Path> files = Files.list(Path.of(dir))) {
      for (final Path model : files.filter(f -> f.toString().endsWith(".model")).sorted()
          .toList()) {
        final Path fixtures = Path.of(model.toString()
            .substring(0, model.toString().length() - ".model".length()) + ".fixtures.tsv");
        assumeTrue(Files.exists(fixtures), "no fixtures for " + model.getFileName());
        models++;
        assertModel(model, fixtures);
      }
    }
    assertTrue(models > 0, "the eval directory contains no models");
  }

  private static void assertModel(Path modelPath, Path fixturesPath) throws IOException {
    final SentencePieceTokenizer tokenizer = SentencePieceTokenizer.load(modelPath);
    int lines = 0;
    try (BufferedReader reader = Files.newBufferedReader(fixturesPath, StandardCharsets.UTF_8)) {
      String line;
      while ((line = reader.readLine()) != null) {
        lines++;
        final String[] cols = line.split("\t", -1);
        final String input = unescape(cols[0]);
        final int count = Integer.parseInt(cols[1]);
        final String context = modelPath.getFileName() + " input <" + input + ">";

        final List<SubwordPiece> actual = tokenizer.encode(input);
        assertEquals(count, actual.size(), context + " piece count; got " + actual);
        for (int i = 0; i < count; i++) {
          final SubwordPiece got = actual.get(i);
          assertEquals(unescape(cols[2 + i * 4]), got.piece(), context + " piece " + i);
          assertEquals(Integer.parseInt(cols[3 + i * 4]), got.id(), context + " id " + i);
          assertEquals(Integer.parseInt(cols[4 + i * 4]), got.start(), context + " start " + i);
          assertEquals(Integer.parseInt(cols[5 + i * 4]), got.end(), context + " end " + i);
        }
        assertEquals(unescape(cols[2 + count * 4]), tokenizer.normalize(input).toString(),
            context + " normalized form");
      }
    }
    assertTrue(lines >= 30, modelPath.getFileName() + " fixtures must not be truncated");
  }

  private static String unescape(String s) {
    final StringBuilder out = new StringBuilder(s.length());
    for (int i = 0; i < s.length(); i++) {
      final char c = s.charAt(i);
      if (c == '\\' && i + 1 < s.length()) {
        i++;
        switch (s.charAt(i)) {
          case 't' -> out.append('\t');
          case 'n' -> out.append('\n');
          case 'r' -> out.append('\r');
          case '\\' -> out.append('\\');
          default -> throw new IllegalArgumentException("bad escape in fixture: " + s);
        }
      } else {
        out.append(c);
      }
    }
    return out.toString();
  }
}
